# Generated by Django 5.0.7 on 2024-07-25 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0002_alter_customuser_email_alter_inventory_total_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='id',
            new_name='inventory_id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_books',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_name', 'author_name')},
        ),
        migrations.AddConstraint(
            model_name='borrowedbook',
            constraint=models.CheckConstraint(check=models.Q(('return_date__isnull', True)), name='unreturned_books'),
        ),
    ]
