# Generated by Django 5.0.7 on 2024-07-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0003_rename_id_inventory_inventory_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
