# Generated by Django 5.0.7 on 2024-07-26 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0004_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total_books',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_name', 'author_name')},
        ),
    ]
