# Generated by Django 5.0.7 on 2024-07-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0008_alter_borrowedbook_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
