# Generated by Django 5.0.7 on 2024-07-31 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0009_alter_borrowedbook_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='borrow_dttm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='return_dttm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
