# Generated by Django 5.0.7 on 2024-07-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('demoapp1', '0010_remove_borrowedbook_borrow_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='User',
            table='demoapp1',
        ),
    ]
