# Generated by Django 5.0.7 on 2024-07-31 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0012_rename_user_customuser_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total_books',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
