# Generated by Django 5.0.7 on 2024-08-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0013_alter_inventory_total_books'),
    ]

    operations = [
        migrations.RenameModel('CustomUser', 'User')
    ]