# Generated by Django 5.0.7 on 2024-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0014_auto_20240801_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
