# Generated by Django 5.0.7 on 2024-08-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0015_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('newuser', 'New User'), ('olduser', 'Old User'), ('admin', 'Admin')], default='olduser', max_length=10),
        ),
    ]
