# Generated by Django 5.0.7 on 2024-08-13 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0016_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 16, 9, 39, 573012, tzinfo=datetime.timezone.utc)),
        ),
    ]
