# Generated by Django 5.0.7 on 2024-08-08 19:44
from django.db import migrations, models
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_groups_and_permissions(apps, schema_editor):
    # Get models and content types
    Book = apps.get_model('demoapp1', 'Book')
    BorrowedBook = apps.get_model('demoapp1', 'BorrowedBook')
    Inventory = apps.get_model('demoapp1', 'Inventory')
    User = apps.get_model('demoapp1', 'User')

    book_ct = ContentType.objects.get_for_model(Book)
    borrowedbook_ct = ContentType.objects.get_for_model(BorrowedBook)
    inventory_ct = ContentType.objects.get_for_model(Inventory)
    user_ct = ContentType.objects.get_for_model(User)

    # Create groups
    newuser_group, _ = Group.objects.get_or_create(name='newuser')
    olduser_group, _ = Group.objects.get_or_create(name='olduser')
    admin_group, _ = Group.objects.get_or_create(name='admin')

    # Create permissions

    # For admin
    view_book_admin = Permission.objects.create(
        codename='view_book_admin',
        name='Admin Can view books',
        content_type=book_ct,
    )

    view_book_newuser = Permission.objects.create(
        codename='view_book_newuser',
        name='New User Can view books',
        content_type=book_ct,
    )

    add_book = Permission.objects.create(
        codename='add_book',
        name='Can add books',
        content_type=book_ct,
    )
    change_book = Permission.objects.create(
        codename='change_book',
        name='Can change books',
        content_type=book_ct,
    )
    delete_book = Permission.objects.create(
        codename='delete_book',
        name='Can delete books',
        content_type=book_ct,
    )

    view_borrowedbook = Permission.objects.create(
        codename='view_borrowedbook',
        name='Can view borrowed books',
        content_type=borrowedbook_ct,
    )

    view_borrowedbook_newuser = Permission.objects.create(
        codename='view_borrowedbook_newuser',
        name='Can view borrowed books',
        content_type=borrowedbook_ct,
    )

    view_inventory = Permission.objects.create(
        codename='view_inventory',
        name='Can view inventory',
        content_type=inventory_ct,
    )

    # Assign permissions to groups
    admin_group.permissions.add(view_book_admin, add_book, change_book, delete_book, view_borrowedbook, view_inventory)
    newuser_group.permissions.add(view_book_newuser, view_borrowedbook_newuser)


def remove_groups_and_permissions(apps, schema_editor):
    Group.objects.filter(name__in=['newuser', 'olduser', 'admin']).delete()
    Permission.objects.filter(codename__in=[
        'view_book', 'add_book', 'change_book', 'delete_book',
        'view_borrowedbook', 'view_inventory'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0018_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, remove_groups_and_permissions),
    ]
