# Generated by Django 5.0.7 on 2024-08-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0019_add_user_groups_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
