# Generated by Django 5.0.7 on 2024-08-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0017_alter_user_created_at'),
        ('demoapp1', '0021_alter_user_role'),
    ]

    operations = [
    ]
