# Generated by Django 5.0.7 on 2024-08-15 06:21

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0022_merge_0017_alter_user_created_at_0021_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 21, 46, 575980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 21, 46, 575980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 21, 46, 575980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 21, 46, 575980, tzinfo=datetime.timezone.utc)),
        ),
    ]
