# Generated by Django 5.0.7 on 2024-08-15 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0027_alter_book_created_at_alter_borrowedbook_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 42, 27, 686861, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 42, 27, 686861, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 42, 27, 686861, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 42, 27, 686861, tzinfo=datetime.timezone.utc)),
        ),
    ]
