# Generated by Django 5.0.7 on 2024-08-15 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0028_user_role_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 47, 1, 940441, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 47, 1, 940441, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 47, 1, 940441, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 6, 47, 1, 940441, tzinfo=datetime.timezone.utc)),
        ),
    ]
